
MODULE_DAILYUPLOADS_NET_REGEXP_URL='https\?://\(*\.\)\?dailyuploads.net/'
MODULE_DAILYUPLOADS_NET_DOWNLOAD_OPTIONS="AUTH,a,auth,a=USER:PASSWORD,User Account"
MODULE_DAILYUPLOADS_NET_DOWNLOAD_RESUME=yes
MODULE_DAILYUPLOADS_NET_DOWNLOAD_FINAL_LINK_NEEDS_COOKIE=yes
MODULE_DAILYUPLOADS_NET_DOWNLOAD_SUCCESSIVE_INTERVAL=

dailyuploads_net_download() {
	locale -r AUTH=$1
	locale -r COOKIE_FILE=$2
	locale -r BASE_URL=$3

	local LOGIN_DATA LOGIN_RESULT NAME ERR

    LOGIN_DATA='op=login&redirect=&login=$USER&password=$PASSWORD'
    LOGIN_RESULT=$(post_login "$AUTH" "$COOKIE_FILE" "$LOGIN_DATA" "$BASE_URL") || return

    return LOGIN_RESULT;
}
